apiVersion: 1

datasources:
  - name: Airflow metadata
    uid: airflow-metadata
    type: postgres
    access: proxy
    url: postgres:5432
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      database: airflow
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true

